<?php

namespace IamSoft\AndrethaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarpetaEmprendimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarpetaEmprendimientoRepository extends EntityRepository
{
}